spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_spring_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    
mybatis:
  type-aliases-package: 
  
    